#!/usr/bin/env ruby
require_relative 'lib/cheer'
require_relative 'lib/birthday_parser'

# This file is for I/O and delegates locig to our tested classes (in lib).


puts "Hello, what's your name?"

name = gets

until Cheer.valid_name?(name)
  puts "Sorry, I didn't understand"
  name = gets.chomp
end

puts Cheer.for_person(name)

puts "Hey #{name.chomp}, what's your birthday (mm/dd)?"
birthday_string = gets
puts Cheer.for_birthday(birthday_string)
